name: Android CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Apk Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-unsigned-${{ GITHUB_REF_NAME }}
        path: app\build\outputs\apk\release\app-release-unsigned.apk
